### ISSUE TITLE
Use electron / js ; implement core

### ISSUE THREAD

**Issue by sartimo** [freakyshine/bitly-painter#1]
Do it in js + electron + sockets?

do it with binary encoded png results

**Comment by danielrlutz** [comment]
The idea with the png output will be implemented.
But we planned to do this project in C# as a console application. Maybe you could work on an actual frontend later on?

**Comment by danielrlutz** [comment]
Thanks for your contribution.

**Comment by sartimo** [comment]
Bro you are c# addicted hahaha
